"""Build the data + cover folder for the album wall (wall/index.html).

Exports every album's art path from the library via `beet export -a` (through
library_snapshot.run_export), then writes:

- wall/covers/<album id>.jpg  -- a downscaled copy of each album's cover art
- wall/albums.js             -- `window.ALBUMS = [...]`, one entry per cover

albums.js is a script (not JSON) so index.html works straight from file://
with no local server -- browsers block fetch() of local JSON files.

Read-only against the library: nothing here touches tags or music files.
Resizing uses macOS's built-in `sips`; without it, covers are copied as-is.
Re-runs are incremental: a cover is only re-rendered when its source art is
newer than the existing copy, and covers for albums no longer in the
library (or no longer matching --query) are removed.

Usage:
    python scripts/build_wall.py [--size 600] [--out wall] [QUERY ...]
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from library_snapshot import run_export  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
SIPS = shutil.which("sips")


def render_cover(src: Path, dst: Path, size: int) -> bool:
    if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
        return True
    tmp = dst.with_suffix(".tmp.jpg")
    if SIPS:
        result = subprocess.run(
            [SIPS, "-s", "format", "jpeg", "-s", "formatOptions", "82",
             "-Z", str(size), str(src), "--out", str(tmp)],
            capture_output=True, check=False,
        )
        if result.returncode != 0 or not tmp.exists():
            tmp.unlink(missing_ok=True)
            return False
    else:
        # Browsers sniff image content, so a PNG saved as .jpg still renders.
        shutil.copyfile(src, tmp)
    tmp.replace(dst)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--size", type=int, default=600,
                        help="max cover edge in pixels (default 600)")
    parser.add_argument("--out", type=Path, default=REPO / "wall",
                        help="wall directory (default: wall/)")
    parser.add_argument("query", nargs="*",
                        help="beets album query, passed through as-is")
    args = parser.parse_args()

    records = run_export(
        args.query, albums=True,
        fields=["id", "album", "albumartist", "year", "artpath"],
    )
    covers_dir = args.out / "covers"
    covers_dir.mkdir(parents=True, exist_ok=True)

    jobs = []
    missing_art = 0
    for r in records:
        src = Path(r.get("artpath") or "")
        if not r.get("artpath") or not src.is_file():
            missing_art += 1
            continue
        jobs.append((r, src, covers_dir / f"{r['id']}.jpg"))

    with ThreadPoolExecutor(max_workers=8) as pool:
        ok = list(pool.map(
            lambda job: render_cover(job[1], job[2], args.size), jobs))

    albums = []
    for (r, _src, dst), good in zip(jobs, ok):
        if not good:
            print(f"warning: could not render {_src}", file=sys.stderr)
            continue
        year = str(r.get("year") or "")
        albums.append({
            "id": int(r["id"]),
            "artist": r.get("albumartist", ""),
            "album": r.get("album", ""),
            "year": int(year) if year.isdigit() and int(year) else None,
            "cover": f"covers/{dst.name}",
        })

    keep = {Path(a["cover"]).name for a in albums}
    stale = [p for p in covers_dir.iterdir() if p.name not in keep]
    for p in stale:
        p.unlink()

    (args.out / "albums.js").write_text(
        "// Generated by scripts/build_wall.py -- do not edit by hand.\n"
        "window.ALBUMS = "
        + json.dumps(albums, ensure_ascii=False, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(f"{len(albums)} covers written to {covers_dir}"
          f" ({missing_art} albums without art skipped,"
          f" {len(stale)} stale covers removed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
